### ISSUE TITLE
Consulta de imagen final

### ISSUE THREAD

**Issue by nicolasegp** [MrMarble/teledock#6]
Estaba viendo tu proyecto y me pareció excelente

Pero tenia una consulta, queria saber porque no usar `scratch` en vez de `alphine`
Si el programa ya esta compilado solo ejecutas el binario en una imagen limpia

> ℹ️ **[Información de scratch](https://hub.docker.com/_/scratch/)**

```Dockerfile
FROM golang:1.14 AS builder
WORKDIR /source
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -o teledock .

FROM scratch
WORKDIR /bot/
COPY --from=builder /source/teledock .
CMD ["./teledock"]
```

Saludos ✌

**Comment by MrMarble** [comment]
Hola Nicolas!
Gracias por el comentario, la verdad es que no lo he hecho porque en su dia no conocia las imagenes `scratch`.

Como es un cambio simple, si quieres puedes crear un PR y así aparecer como colaborador, de lo contrario, marca como cerrado el issue y ya lo hago yo 👍🏽 

Gracias!
